[package]
name = "redis_with_rust"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = {version = "0.21.3", features = ["tokio-comp"]}
actix-web = "4.0.0-beta.9"